### ISSUE TITLE
origin/dev: Commit 7b820ad18 breaks Android build

### ISSUE THREAD

**Issue by lpechacek** [OpenOrienteering/mapper#1065]
While building Mapper Android/ARM version with Superbuild, the following error pops up:
```
/tmp/android-build/source/openorienteering-mapper-master/src/core/symbols/symbol.cpp: In copy constructor 'OpenOrienteering::Symbol::Symbol(const OpenOrienteering::Symbol&)':
/tmp/android-build/source/openorienteering-mapper-master/src/core/symbols/symbol.cpp:78:37: error: cannot convert 'const std::array<int, 3u>' to 'int' in initialization
 , is_protected { proto.is_protected }
                                     ^
```

Bisected down to 7b820ad18c3b9eadc03aeb3d8d1e11e605aa2b8c.

Please note that there are more errors with current origin/dev. Compiler complains about undefined `rbegin()/rend()` in the same file.

**Comment by dg0yt** [comment]
I'm sorry for that. We need a more modern Android toolchain than the deprecated gcc 4.9. So far the size of the resulting binaries with Clang on ARM was an issue for Qt (and Firefox) but there seems to be a solution now: https://github.com/android-ndk/ndk/issues/133. Still need to put this in a Qt 5.9 superbuild.

**Comment by lpechacek** [comment]
No need for apologies. I'd welcome an NDK update though. :)

**Comment by dg0yt** [comment]
Maybe we shouldn't be too optimistic about an NDK update with Qt:
http://lists.qt-project.org/pipermail/android-development/2018-March/001010.html

**Comment by dg0yt** [comment]
Finally, I succeeded in building `dev` with Qt 5.9 with Android NDK r18b / Clang / libc++ (OpenOrienteering Superbuild). APK size is reasonable, and the app runs indeed. However, compile time may have increased.

**Comment by dg0yt** [comment]
NDK r18b is now established, at least in CI for v0.9.0.
